---
- name: Create a Fibre Channel Network
  # vars:
  #   files:
  #     - "{{ playbook_dir }}/oneview_config.json"
    # config: "{{ playbook_dir }}/oneview_config.json"
    # network_name: 'Ansible Test FC Network'
  oneview_fc_network:
      config: "{{ config }}"
      state: present
      validate_etag: False
      data:
        name: "{{ network_name }}"
        fabricType: 'FabricAttach'
        linkStabilityTime: '30'
        autoLoginRedistribution: true
  delegate_to: localhost
  register: fc_network_1
