---
- name: Create a Fibre Channel Network
  oneview_fc_network:
      config: "{{ config }}"
      state: present
      validate_etag: False
      data:
        name: "{{ network_name }}"
        fabricType: 'FabricAttach'
        linkStabilityTime: '30'
        autoLoginRedistribution: true
  delegate_to: localhost
  register: fc_network_1
